set_mode:
  description: Sets duka fan mode.
  fields:
    entity_id:
      description: Name of the entity to set
      example: "fan.dukaone"
    mode:
      description: Mode in,out,inout
      example: "inout"
reset_filter_timer:
  description: Reset the filter timer to 90 days
  fields:
    entity_id:
      description: Name of the entity to reset
      example: "fan.dukaone"
set_manual_speed:
  description: Set the fan speed manaually
  fields:
    entity_id:
      description: Name of the entity to reset
      example: "fan.dukaone"
    manual_speed:
      description: Manual speed 0-255
      example: 100
